import type { Agent } from "./types"

export function createEmptyAgent(): Agent {
  const id = `agent_${Date.now()}`
  return {
    id,
    name: "未命名智能体",
    variableName: "untitled_agent",
    author: "Default User",
    model: "kimi-k2.5",
    maxSteps: 20,
    runSummary: "否",
    description: "",
    businessLogic: "",
    promptTemplate: "系统默认",
    role: "",
    requirements: "",
    examples: "",
    openingMessage: "",
    exampleQuestions: [],
    tools: [],
    skills: [],
    collaborators: [],
    status: "draft",
    updatedAt: new Date().toISOString(),
  }
}

// 将外部 JSON 归一化为合法的 Agent，缺失字段使用默认值，始终生成新 id 与草稿状态
export function normalizeImportedAgent(raw: unknown): Agent {
  const base = createEmptyAgent()
  const data = (raw && typeof raw === "object" ? raw : {}) as Partial<Agent>
  return {
    ...base,
    ...data,
    id: `agent_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    name: typeof data.name === "string" && data.name.trim() ? data.name : "导入的智能体",
    tools: Array.isArray(data.tools) ? data.tools : [],
    skills: Array.isArray(data.skills) ? data.skills : [],
    exampleQuestions: Array.isArray(data.exampleQuestions) ? data.exampleQuestions : [],
    collaborators: Array.isArray(data.collaborators) ? data.collaborators : [],
    status: "draft",
    updatedAt: new Date().toISOString(),
  }
}

export const SAMPLE_AGENTS: Agent[] = [
  {
    id: "agent_excel",
    name: "Excel文档创建助手",
    variableName: "excel_creation_assistant",
    author: "Default User",
    model: "kimi-k2.5",
    maxSteps: 20,
    runSummary: "否",
    description:
      "你是一个Excel文档创建助手，能够帮助用户创建各类电子表格并提供专业的表格设计、公式编写和数据整理服务。你可以根据需求生成结构清晰的Excel文档，协助完成数据录入、格式优化和计算分析等工作。",
    businessLogic: "excel文档创建助手",
    promptTemplate: "系统默认",
    role: "专业的电子表格创建与数据处理专家。",
    requirements: "用户需提供数据内容或表格结构需求。",
    examples: "用户：帮我做一份月度销售统计表。",
    openingMessage: "你好！我是 Excel 文档创建助手，可以帮你快速创建各类电子表格。请告诉我你需要什么样的表格。",
    exampleQuestions: ["帮我做一份月度销售统计表", "创建一个项目进度跟踪表", "生成员工考勤记录表格"],
    tools: ["create_docx", "query"],
    skills: ["数据清洗", "数据聚合", "模板填充"],
    collaborators: [],
    status: "published",
    updatedAt: "2026-05-20T09:00:00.000Z",
  },
  {
    id: "agent_writer",
    name: "智能写作助手",
    variableName: "writing_assistant",
    author: "Default User",
    model: "claude-opus-4.6",
    maxSteps: 15,
    runSummary: "是",
    description: "帮助用户撰写、润色和优化各类文案，包括公文、营销文案、邮件等多种文体。",
    businessLogic: "智能写作与文案润色",
    promptTemplate: "通用助手",
    role: "资深文案与内容创作专家。",
    requirements: "用户需提供写作主题或原始文本。",
    examples: "用户：帮我润色这封商务邮件。",
    openingMessage: "你好！我是智能写作助手，擅长撰写和润色各类文案。有什么需要我帮忙的吗？",
    exampleQuestions: ["帮我润色这封商务邮件", "写一份产品发布的营销文案", "把这段话改得更正式一些"],
    tools: ["create_docx", "web_search"],
    skills: ["文档摘要", "邮件撰写", "格式转换"],
    collaborators: [],
    status: "published",
    updatedAt: "2026-05-18T14:30:00.000Z",
  },
  {
    id: "agent_data",
    name: "数据分析专家",
    variableName: "data_analyst",
    author: "Default User",
    model: "gpt-5-mini",
    maxSteps: 30,
    runSummary: "是",
    description: "对接数据库与文件，进行数据清洗、统计分析与可视化报告生成。",
    businessLogic: "数据分析与可视化",
    promptTemplate: "数据分析",
    role: "数据科学与商业分析专家。",
    requirements: "用户需提供数据源或分析目标。",
    examples: "用户：分析这份用户留存数据并给出结论。",
    openingMessage: "你好！我是数据分析专家，可以帮你完成数据清洗、统计分析和可视化报告。请提供你的数据或分析目标。",
    exampleQuestions: ["分析这份用户留存数据并给出结论", "对销售数据做趋势分析", "找出导致转化率下降的原因"],
    tools: ["query", "doc_search", "image_understand"],
    skills: ["数据清洗", "趋势分析", "决策建议"],
    collaborators: [],
    status: "draft",
    updatedAt: "2026-05-22T11:15:00.000Z",
  },
]
